version: '3'
services:
  application:
    container_name: $name;format="normalize"$
    image: $name;format="normalize"$:latest
    environment:
      - HTTP_PORT=8080
    ports:
      - 80:8080
    volumes:
      # verify permissions e.g. chmod 777 /vol/log/$name;format="normalize"$
      - /vol/log/$name;format="normalize"$:/opt/docker/log
